### ISSUE TITLE
Issues with jupyter 4.0

### ISSUE THREAD

**Issue by garrison** [sjpfenninger/ipython-extensions#2]
It looks like the syntax for loading modules [has changed again](https://github.com/jupyter/notebook/issues/226) in jupyter 4.0:

``` js
$([IPython.events]).on("app_initialized.NotebookApp", function () {
    require(['base/js/utils'], function(utils) {
        utils.load_extensions('notify');
    });
});
```

~~After fixing this, the notebook and extension load correctly, but I still don't see the notification permissions in the toolbar.~~  Actually, now everything seems to work once I change `custom.js` as mentioned above.

**Comment by sjpfenninger** [comment]
This is addressed by a much simpler way to load extensions as described in 6ad96d0.
